version: '3.4'
services:
  php:
    image: devilbox/php-fpm-7.4
    volumes:
      - ./:/var/www/default/htdocs

  ngnix:
    image: devilbox/nginx-stable
    volumes:
      - ./:/var/www/default/htdocs
    ports:
      - '8080:80'
    environment:
      PHP_FPM_ENABLE: 1
      PHP_FPM_SERVER_ADDR: php
    links:
      - php
